import type { AddOn, BookingState, Court, Customer, Reservation } from "./booking-types";

export const STORAGE_VERSION = 1;
export const STORAGE_KEY = "smashcourt-booking-state-v1";

export const courts: Court[] = [
  {
    id: "court-agave",
    name: "Court 1 - Agave",
    shortName: "Agave",
    type: "Outdoor",
    surface: "Rubberized Surface",
    hourlyRate: 300,
    theme: "sage",
    amenities: ["Fan-cooled sideline", "Evening lights", "Hydration station"],
  },
  {
    id: "court-bandera",
    name: "Court 2 - Bandera",
    shortName: "Bandera",
    type: "Outdoor",
    surface: "Rubberized Surface",
    hourlyRate: 300,
    theme: "sky",
    amenities: ["Shaded bench", "Evening lights", "Ball machine ready"],
  },
  {
    id: "court-cebu",
    name: "Court 3 - Cebu",
    shortName: "Cebu",
    type: "Indoor",
    surface: "Hardwood Floor",
    hourlyRate: 450,
    theme: "peach",
    amenities: ["Air conditioned", "Premium floor", "Scoreboard"],
  },
  {
    id: "court-datu",
    name: "Court 4 - Datu",
    shortName: "Datu",
    type: "Indoor",
    surface: "Hardwood Floor",
    hourlyRate: 450,
    theme: "butter",
    amenities: ["Air conditioned", "Premium floor", "Coaching lane"],
  },
];

export const addOns: AddOn[] = [
  {
    id: "paddle-rental",
    name: "Paddle rental",
    price: 120,
    description: "Two premium paddles for the session.",
  },
  {
    id: "ball-tube",
    name: "Ball tube",
    price: 80,
    description: "Fresh three-ball tube for match play.",
  },
  {
    id: "locker",
    name: "Locker",
    price: 60,
    description: "Secure locker access during your booking.",
  },
  {
    id: "coach-warmup",
    name: "Coach warm-up",
    price: 350,
    description: "Fifteen-minute guided warm-up before play.",
  },
];

const customers: Customer[] = [
  {
    id: "customer-ana",
    name: "Ana Reyes",
    phone: "0917 234 0901",
    email: "ana.reyes@example.com",
    skillLevel: "intermediate",
  },
  {
    id: "customer-jules",
    name: "Jules Tan",
    phone: "0918 889 4210",
    email: "jules.tan@example.com",
    skillLevel: "beginner",
  },
  {
    id: "customer-miko",
    name: "Miko Lim",
    phone: "0920 144 5522",
    email: "miko.lim@example.com",
    skillLevel: "advanced",
  },
  {
    id: "customer-bianca",
    name: "Bianca Cruz",
    phone: "0916 402 1188",
    email: "bianca.cruz@example.com",
    skillLevel: "open-play",
  },
];

const reservations: Reservation[] = [
  {
    id: "reservation-001",
    courtId: "court-agave",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 8,
    durationHours: 1,
    addOnIds: ["paddle-rental"],
    status: "checked-in",
    paymentStatus: "paid",
    total: 420,
    createdAt: "2026-04-20T09:15:00.000Z",
  },
  {
    id: "reservation-002",
    courtId: "court-agave",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 9,
    durationHours: 1,
    addOnIds: ["ball-tube"],
    status: "booked",
    paymentStatus: "paid",
    total: 380,
    createdAt: "2026-04-21T13:05:00.000Z",
  },
  {
    id: "reservation-003",
    courtId: "court-agave",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 14,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "unpaid",
    total: 300,
    createdAt: "2026-04-22T07:42:00.000Z",
  },
  {
    id: "reservation-004",
    courtId: "court-bandera",
    customerId: "customer-bianca",
    date: "2026-04-24",
    startHour: 10,
    durationHours: 1,
    addOnIds: ["locker"],
    status: "booked",
    paymentStatus: "paid",
    total: 360,
    createdAt: "2026-04-22T11:12:00.000Z",
  },
  {
    id: "reservation-005",
    courtId: "court-bandera",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 11,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "paid",
    total: 300,
    createdAt: "2026-04-23T03:25:00.000Z",
  },
  {
    id: "reservation-006",
    courtId: "court-bandera",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 12,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "unpaid",
    total: 300,
    createdAt: "2026-04-23T05:34:00.000Z",
  },
  {
    id: "reservation-007",
    courtId: "court-cebu",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 7,
    durationHours: 1,
    addOnIds: ["coach-warmup"],
    status: "completed",
    paymentStatus: "paid",
    total: 800,
    createdAt: "2026-04-18T16:15:00.000Z",
  },
  {
    id: "reservation-008",
    courtId: "court-cebu",
    customerId: "customer-bianca",
    date: "2026-04-24",
    startHour: 13,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "paid",
    total: 450,
    createdAt: "2026-04-21T04:17:00.000Z",
  },
  {
    id: "reservation-009",
    courtId: "court-cebu",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 15,
    durationHours: 1,
    addOnIds: ["locker"],
    status: "booked",
    paymentStatus: "paid",
    total: 510,
    createdAt: "2026-04-22T08:07:00.000Z",
  },
  {
    id: "reservation-010",
    courtId: "court-datu",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 9,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "unpaid",
    total: 450,
    createdAt: "2026-04-20T07:30:00.000Z",
  },
  {
    id: "reservation-011",
    courtId: "court-datu",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 16,
    durationHours: 1,
    addOnIds: ["ball-tube"],
    status: "booked",
    paymentStatus: "paid",
    total: 530,
    createdAt: "2026-04-21T14:40:00.000Z",
  },
  {
    id: "reservation-012",
    courtId: "court-agave",
    customerId: "customer-bianca",
    date: "2026-04-25",
    startHour: 7,
    durationHours: 1,
    addOnIds: [],
    status: "booked",
    paymentStatus: "paid",
    total: 300,
    createdAt: "2026-04-22T10:20:00.000Z",
  },
  {
    id: "reservation-013",
    courtId: "court-bandera",
    customerId: "customer-ana",
    date: "2026-04-25",
    startHour: 17,
    durationHours: 1,
    addOnIds: ["paddle-rental"],
    status: "booked",
    paymentStatus: "paid",
    total: 420,
    createdAt: "2026-04-22T10:28:00.000Z",
  },
  {
    id: "reservation-014",
    courtId: "court-cebu",
    customerId: "customer-jules",
    date: "2026-04-26",
    startHour: 18,
    durationHours: 1,
    addOnIds: ["locker"],
    status: "booked",
    paymentStatus: "unpaid",
    total: 510,
    createdAt: "2026-04-23T06:11:00.000Z",
  },
  {
    id: "reservation-015",
    courtId: "court-datu",
    customerId: "customer-miko",
    date: "2026-04-27",
    startHour: 12,
    durationHours: 1,
    addOnIds: ["coach-warmup"],
    status: "booked",
    paymentStatus: "paid",
    total: 800,
    createdAt: "2026-04-23T08:45:00.000Z",
  },
];

export function buildInitialBookingState(): BookingState {
  return {
    version: STORAGE_VERSION,
    courts: structuredClone(courts),
    addOns: structuredClone(addOns),
    customers: structuredClone(customers),
    reservations: structuredClone(reservations),
    closures: [
      {
        id: "closure-maintenance-001",
        date: "2026-04-30",
        courtIds: ["court-cebu"],
        reason: "Floor maintenance",
      },
    ],
    openHour: 6,
    closeHour: 22,
  };
}
