import type {
  AddOn,
  AdminActivity,
  AdminProfile,
  BillingSummary,
  BookingState,
  Court,
  Customer,
  GalleryItem,
  OperatingHour,
  PricingRule,
  PrivacyStatement,
  Reservation,
} from "./booking-types";

export const STORAGE_VERSION = 4;
export const STORAGE_KEY = "smashcourt-booking-state-v4";

export const courts: Court[] = [
  {
    id: "court-agave",
    name: "Court 1 - Agave",
    shortName: "Agave",
    type: "Outdoor",
    surface: "Rubberized Surface",
    hourlyRate: 300,
    theme: "sage",
    amenities: ["Fan-cooled sideline", "Evening lights", "Hydration station"],
  },
  {
    id: "court-bandera",
    name: "Court 2 - Bandera",
    shortName: "Bandera",
    type: "Outdoor",
    surface: "Rubberized Surface",
    hourlyRate: 300,
    theme: "sky",
    amenities: ["Shaded bench", "Evening lights", "Ball machine ready"],
  },
  {
    id: "court-cebu",
    name: "Court 3 - Cebu",
    shortName: "Cebu",
    type: "Indoor",
    surface: "Hardwood Floor",
    hourlyRate: 450,
    theme: "peach",
    amenities: ["Air conditioned", "Premium floor", "Scoreboard"],
  },
  {
    id: "court-datu",
    name: "Court 4 - Datu",
    shortName: "Datu",
    type: "Indoor",
    surface: "Hardwood Floor",
    hourlyRate: 450,
    theme: "butter",
    amenities: ["Air conditioned", "Premium floor", "Coaching lane"],
  },
];

export const addOns: AddOn[] = [
  {
    id: "paddle-rental",
    name: "Paddle rental",
    price: 120,
    description: "Two premium paddles for the session.",
  },
  {
    id: "ball-tube",
    name: "Ball tube",
    price: 80,
    description: "Fresh three-ball tube for match play.",
  },
  {
    id: "locker",
    name: "Locker",
    price: 60,
    description: "Secure locker access during your booking.",
  },
  {
    id: "coach-warmup",
    name: "Coach warm-up",
    price: 350,
    description: "Fifteen-minute guided warm-up before play.",
  },
];

const customers: Customer[] = [
  {
    id: "customer-ana",
    name: "Ana Reyes",
    phone: "0917 234 0901",
    email: "ana.reyes@example.com",
    skillLevel: "intermediate",
  },
  {
    id: "customer-jules",
    name: "Jules Tan",
    phone: "0918 889 4210",
    email: "jules.tan@example.com",
    skillLevel: "beginner",
  },
  {
    id: "customer-miko",
    name: "Miko Lim",
    phone: "0920 144 5522",
    email: "miko.lim@example.com",
    skillLevel: "advanced",
  },
  {
    id: "customer-bianca",
    name: "Bianca Cruz",
    phone: "0916 402 1188",
    email: "bianca.cruz@example.com",
    skillLevel: "open-play",
  },
];

const reservations: Reservation[] = [
  {
    id: "reservation-001",
    courtId: "court-agave",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 8,
    durationHours: 1,
    addOnIds: ["paddle-rental"],
    paymentMethod: "credit-debit-card",
    status: "checked-in",
    paymentStatus: "paid",
    total: 420,
    createdAt: "2026-04-20T09:15:00.000Z",
  },
  {
    id: "reservation-002",
    courtId: "court-agave",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 9,
    durationHours: 1,
    addOnIds: ["ball-tube"],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "paid",
    total: 380,
    createdAt: "2026-04-21T13:05:00.000Z",
  },
  {
    id: "reservation-003",
    courtId: "court-agave",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 14,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "unpaid",
    total: 300,
    createdAt: "2026-04-22T07:42:00.000Z",
  },
  {
    id: "reservation-004",
    courtId: "court-bandera",
    customerId: "customer-bianca",
    date: "2026-04-24",
    startHour: 10,
    durationHours: 1,
    addOnIds: ["locker"],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "paid",
    total: 360,
    createdAt: "2026-04-22T11:12:00.000Z",
  },
  {
    id: "reservation-005",
    courtId: "court-bandera",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 11,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "paid",
    total: 300,
    createdAt: "2026-04-23T03:25:00.000Z",
  },
  {
    id: "reservation-006",
    courtId: "court-bandera",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 12,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "unpaid",
    total: 300,
    createdAt: "2026-04-23T05:34:00.000Z",
  },
  {
    id: "reservation-007",
    courtId: "court-cebu",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 7,
    durationHours: 1,
    addOnIds: ["coach-warmup"],
    paymentMethod: "credit-debit-card",
    status: "completed",
    paymentStatus: "paid",
    total: 800,
    createdAt: "2026-04-18T16:15:00.000Z",
  },
  {
    id: "reservation-008",
    courtId: "court-cebu",
    customerId: "customer-bianca",
    date: "2026-04-24",
    startHour: 13,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "paid",
    total: 450,
    createdAt: "2026-04-21T04:17:00.000Z",
  },
  {
    id: "reservation-009",
    courtId: "court-cebu",
    customerId: "customer-ana",
    date: "2026-04-24",
    startHour: 15,
    durationHours: 1,
    addOnIds: ["locker"],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "paid",
    total: 510,
    createdAt: "2026-04-22T08:07:00.000Z",
  },
  {
    id: "reservation-010",
    courtId: "court-datu",
    customerId: "customer-jules",
    date: "2026-04-24",
    startHour: 9,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "unpaid",
    total: 450,
    createdAt: "2026-04-20T07:30:00.000Z",
  },
  {
    id: "reservation-011",
    courtId: "court-datu",
    customerId: "customer-miko",
    date: "2026-04-24",
    startHour: 16,
    durationHours: 1,
    addOnIds: ["ball-tube"],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "paid",
    total: 530,
    createdAt: "2026-04-21T14:40:00.000Z",
  },
  {
    id: "reservation-012",
    courtId: "court-agave",
    customerId: "customer-bianca",
    date: "2026-04-25",
    startHour: 7,
    durationHours: 1,
    addOnIds: [],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "paid",
    total: 300,
    createdAt: "2026-04-22T10:20:00.000Z",
  },
  {
    id: "reservation-013",
    courtId: "court-bandera",
    customerId: "customer-ana",
    date: "2026-04-25",
    startHour: 17,
    durationHours: 1,
    addOnIds: ["paddle-rental"],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "paid",
    total: 420,
    createdAt: "2026-04-22T10:28:00.000Z",
  },
  {
    id: "reservation-014",
    courtId: "court-cebu",
    customerId: "customer-jules",
    date: "2026-04-26",
    startHour: 18,
    durationHours: 1,
    addOnIds: ["locker"],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "unpaid",
    total: 510,
    createdAt: "2026-04-23T06:11:00.000Z",
  },
  {
    id: "reservation-015",
    courtId: "court-datu",
    customerId: "customer-miko",
    date: "2026-04-27",
    startHour: 12,
    durationHours: 1,
    addOnIds: ["coach-warmup"],
    paymentMethod: "credit-debit-card",
    status: "booked",
    paymentStatus: "paid",
    total: 800,
    createdAt: "2026-04-23T08:45:00.000Z",
  },
  {
    id: "reservation-016",
    courtId: "court-agave",
    customerId: "customer-ana",
    date: "2026-04-28",
    startHour: 9,
    durationHours: 1,
    addOnIds: ["ball-tube"],
    paymentMethod: "gcash",
    status: "booked",
    paymentStatus: "paid",
    total: 380,
    createdAt: "2026-04-24T03:20:00.000Z",
  },
];

const operatingHours: OperatingHour[] = [
  { day: "monday", label: "Mon", openHour: 13, closeHour: 22, slotMinutes: 60 },
  { day: "tuesday", label: "Tue", openHour: 13, closeHour: 17, slotMinutes: 60 },
  { day: "wednesday", label: "Wed", openHour: 13, closeHour: 22, slotMinutes: 60 },
  { day: "thursday", label: "Thu", openHour: 13, closeHour: 17, slotMinutes: 60 },
  { day: "friday", label: "Fri", openHour: 13, closeHour: 22, slotMinutes: 60 },
  { day: "saturday", label: "Sat", openHour: 8, closeHour: 22, slotMinutes: 60 },
  { day: "sunday", label: "Sun", openHour: 8, closeHour: 22, slotMinutes: 60 },
];

const pricingRules: PricingRule[] = [
  {
    id: "pricing-weekday-evening",
    day: "monday",
    label: "Weekday evening",
    startHour: 13,
    endHour: 22,
    price: 700,
    courtIds: ["court-agave", "court-bandera", "court-cebu", "court-datu"],
  },
  {
    id: "pricing-tuesday-short",
    day: "tuesday",
    label: "Short day",
    startHour: 13,
    endHour: 17,
    price: 700,
    courtIds: ["court-agave", "court-bandera"],
  },
  {
    id: "pricing-weekend",
    day: "saturday",
    label: "Weekend day pass",
    startHour: 8,
    endHour: 17,
    price: 850,
    courtIds: ["court-cebu", "court-datu"],
  },
];

const privacyStatements: PrivacyStatement[] = [
  {
    id: "privacy-main",
    title: "Website privacy notice",
    channel: "Website",
    status: "published",
    version: "v2.1",
    updatedAt: "2026-04-18",
  },
  {
    id: "privacy-booking",
    title: "Booking consent copy",
    channel: "Booking Form",
    status: "review",
    version: "v1.7",
    updatedAt: "2026-04-21",
  },
  {
    id: "privacy-email",
    title: "Email marketing consent",
    channel: "Email",
    status: "draft",
    version: "v1.2",
    updatedAt: "2026-04-22",
  },
];

const galleryItems: GalleryItem[] = [
  {
    id: "gallery-agave",
    title: "Agave evening session",
    category: "Court",
    status: "published",
    accent: "sage",
    updatedAt: "2026-04-18",
  },
  {
    id: "gallery-clinic",
    title: "Saturday beginner clinic",
    category: "Event",
    status: "published",
    accent: "peach",
    updatedAt: "2026-04-20",
  },
  {
    id: "gallery-lockers",
    title: "Locker and shower area",
    category: "Facility",
    status: "draft",
    accent: "sky",
    updatedAt: "2026-04-22",
  },
];

const billingSummary: BillingSummary = {
  plan: "SmashCourt Pro",
  nextInvoiceDate: "2026-05-01",
  paymentMethod: "Visa ending 4242",
  monthlyTotal: 2490,
  invoices: [
    {
      id: "INV-1042",
      date: "2026-04-01",
      description: "Booking platform subscription",
      amount: 2490,
      status: "paid",
    },
    {
      id: "INV-1043",
      date: "2026-05-01",
      description: "Upcoming monthly subscription",
      amount: 2490,
      status: "upcoming",
    },
  ],
};

const adminProfile: AdminProfile = {
  companyName: "SmashCourt Pickleball",
  adminName: "Cala Puerto",
  adminEmail: "admin@smashcourt.example",
  role: "Company Admin",
};

const adminActivity: AdminActivity[] = [
  {
    id: "activity-001",
    label: "Pricing updated",
    detail: "Weekend indoor courts set to ₱850.",
    createdAt: "2026-04-24T06:30:00.000Z",
  },
  {
    id: "activity-002",
    label: "Booking checked in",
    detail: "Ana Reyes checked in for Court 1 - Agave.",
    createdAt: "2026-04-24T00:05:00.000Z",
  },
  {
    id: "activity-003",
    label: "Gallery draft added",
    detail: "Locker and shower area added as a draft item.",
    createdAt: "2026-04-23T12:20:00.000Z",
  },
];

export function buildInitialBookingState(): BookingState {
  return {
    version: STORAGE_VERSION,
    courts: structuredClone(courts),
    addOns: structuredClone(addOns),
    customers: structuredClone(customers),
    reservations: withMockPaymentReceipts(reservations),
    closures: [
      {
        id: "closure-maintenance-001",
        date: "2026-04-30",
        courtIds: ["court-cebu"],
        reason: "Floor maintenance",
      },
    ],
    operatingHours: structuredClone(operatingHours),
    pricingRules: structuredClone(pricingRules),
    privacyStatements: structuredClone(privacyStatements),
    galleryItems: structuredClone(galleryItems),
    billingSummary: structuredClone(billingSummary),
    adminProfile: structuredClone(adminProfile),
    adminActivity: structuredClone(adminActivity),
    openHour: 6,
    closeHour: 22,
  };
}

function withMockPaymentReceipts(items: Reservation[]): Reservation[] {
  return structuredClone(items).map((reservation, index) => {
    if (reservation.paymentStatus !== "paid") {
      return reservation;
    }

    const sequence = reservation.id.match(/\d+$/)?.[0] ?? String(index + 1).padStart(3, "0");
    const paymentDate = reservation.date.replaceAll("-", "");

    return {
      ...reservation,
      invoiceNumber: reservation.invoiceNumber ?? `INV-${paymentDate}-${sequence}`,
      paymentReference: reservation.paymentReference ?? `PAY-${paymentDate}-${sequence}`,
      paidAt: reservation.paidAt ?? reservation.createdAt,
    };
  });
}
